// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tiptopchefs.domain;

import com.tiptopchefs.domain.MenuItemOrderDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MenuItemOrderDataOnDemand_Roo_Configurable {
    
    declare @type: MenuItemOrderDataOnDemand: @Configurable;
    
}
