// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tiptopchefs.domain;

import com.tiptopchefs.domain.MenuItemOrderIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MenuItemOrderIntegrationTest_Roo_Configurable {
    
    declare @type: MenuItemOrderIntegrationTest: @Configurable;
    
}
