// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tiptopchefs.domain;

import com.tiptopchefs.domain.MenuItemOrder;
import com.tiptopchefs.domain.MenuItemOrderDataOnDemand;
import com.tiptopchefs.domain.MenuItemOrderIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MenuItemOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MenuItemOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MenuItemOrderIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MenuItemOrderIntegrationTest: @Transactional;
    
    @Autowired
    MenuItemOrderDataOnDemand MenuItemOrderIntegrationTest.dod;
    
    @Test
    public void MenuItemOrderIntegrationTest.testCountMenuItemOrders() {
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", dod.getRandomMenuItemOrder());
        long count = MenuItemOrder.countMenuItemOrders();
        Assert.assertTrue("Counter for 'MenuItemOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testFindMenuItemOrder() {
        MenuItemOrder obj = dod.getRandomMenuItemOrder();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to provide an identifier", id);
        obj = MenuItemOrder.findMenuItemOrder(id);
        Assert.assertNotNull("Find method for 'MenuItemOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MenuItemOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testFindAllMenuItemOrders() {
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", dod.getRandomMenuItemOrder());
        long count = MenuItemOrder.countMenuItemOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'MenuItemOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MenuItemOrder> result = MenuItemOrder.findAllMenuItemOrders();
        Assert.assertNotNull("Find all method for 'MenuItemOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MenuItemOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testFindMenuItemOrderEntries() {
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", dod.getRandomMenuItemOrder());
        long count = MenuItemOrder.countMenuItemOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MenuItemOrder> result = MenuItemOrder.findMenuItemOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MenuItemOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MenuItemOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testFlush() {
        MenuItemOrder obj = dod.getRandomMenuItemOrder();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to provide an identifier", id);
        obj = MenuItemOrder.findMenuItemOrder(id);
        Assert.assertNotNull("Find method for 'MenuItemOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMenuItemOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MenuItemOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testMergeUpdate() {
        MenuItemOrder obj = dod.getRandomMenuItemOrder();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to provide an identifier", id);
        obj = MenuItemOrder.findMenuItemOrder(id);
        boolean modified =  dod.modifyMenuItemOrder(obj);
        Integer currentVersion = obj.getVersion();
        MenuItemOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MenuItemOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", dod.getRandomMenuItemOrder());
        MenuItemOrder obj = dod.getNewTransientMenuItemOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MenuItemOrder' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'MenuItemOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MenuItemOrderIntegrationTest.testRemove() {
        MenuItemOrder obj = dod.getRandomMenuItemOrder();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MenuItemOrder' failed to provide an identifier", id);
        obj = MenuItemOrder.findMenuItemOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MenuItemOrder' with identifier '" + id + "'", MenuItemOrder.findMenuItemOrder(id));
    }
    
}
