// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tiptopchefs.domain;

import com.tiptopchefs.domain.Menu;

privileged aspect Menu_Roo_JavaBean {
    
    public String Menu.getName() {
        return this.name;
    }
    
    public void Menu.setName(String name) {
        this.name = name;
    }
    
}
