// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tiptopchefs.domain;

import com.tiptopchefs.domain.MenuItem;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MenuItem_Roo_Configurable {
    
    declare @type: MenuItem: @Configurable;
    
}
